# Performing Principal Component Analysis (PCA) - Lab

## Introduction

Now that you have high level overview of PCA as well as some of the details in the algorithm itself, its time to practice implementing PCA on your own using the NumPy package. 

## Objectives

You will be able to:
    
* Implement PCA from scratch using NumPy

## Import the Data

To start, import the data stored in the file 'foodusa.csv'.

In [6]:
import pandas as pd
import numpy as np

data = pd.read_csv('foodusa.csv')
data.head()

City  Bread  Burger  Milk  Oranges  Tomatoes
0    ATLANTA   24.5    94.5  73.9     80.1      41.6
1  BALTIMORE   26.5    91.0  67.5     74.6      53.3
2     BOSTON   29.7   100.8  61.4    104.0      59.6
3    BUFFALO   22.8    86.6  65.3    118.4      51.2
4    CHICAGO   26.7    86.7  62.7    105.9      51.2

## Normalize the Data

Next, normalize your data by subtracting the feature mean from each of the columns

In [10]:
data = data.drop('City',axis=1)

In [11]:
mean_centered = data - data.mean()

## Calculate the Covariance Matrix

The next step for PCA is to calculate to covariance matrix for your normalized data. Do so here.

In [20]:
cov = np.cov([mean_centered.Bread, mean_centered.Burger, mean_centered.Milk, mean_centered.Oranges, mean_centered.Tomatoes])


In [21]:
cov

array([[  6.2844664 ,  12.91096838,   5.71905138,   1.31037549,
          7.28513834],
       [ 12.91096838,  57.07711462,  17.50752964,  22.69187747,
         36.29478261],
       [  5.71905138,  17.50752964,  48.30588933,  -0.27503953,
         13.44347826],
       [  1.31037549,  22.69187747,  -0.27503953, 202.75628458,
         38.76241107],
       [  7.28513834,  36.29478261,  13.44347826,  38.76241107,
         57.80055336]])

## Calculate the Eigenvectors

Next, calculate the eigenvectors for your covariance matrix.

In [22]:
eigen_value, eigen_vector = np.linalg.eig(cov)


In [23]:
eigen_vector

array([[-0.02848905, -0.16532108, -0.96716354, -0.18972574,  0.02135748],
       [-0.2001224 , -0.63218494,  0.24877074, -0.65862454,  0.25420475],
       [-0.0416723 , -0.44215032,  0.03606094,  0.10765906, -0.88874949],
       [-0.93885906,  0.31435473, -0.01521357, -0.06904699, -0.12135003],
       [-0.27558389, -0.52791603, -0.03429221,  0.71684022,  0.36100184]])

In [24]:
eigen_value
#highest: first

array([218.99867893,  91.72316894,   3.02922934,  20.81054128,
        37.66268981])

## Sorting the Eigenvectors to Determine Primary Components

Great! Now that you have the eigenvectors and their associated eigenvalues, sort the eigenvectors based on their eigenvalues!

In [26]:
e_indices = np.argsort(eigen_value)[::-1] #Get the index values of the sorted eigenvalues
eigenvectors_sorted = eigen_vector[:,e_indices]
eigenvectors_sorted


array([[-0.02848905, -0.16532108,  0.02135748, -0.18972574, -0.96716354],
       [-0.2001224 , -0.63218494,  0.25420475, -0.65862454,  0.24877074],
       [-0.0416723 , -0.44215032, -0.88874949,  0.10765906,  0.03606094],
       [-0.93885906,  0.31435473, -0.12135003, -0.06904699, -0.01521357],
       [-0.27558389, -0.52791603,  0.36100184,  0.71684022, -0.03429221]])

## Reprojecting the Data

Finally, reproject the dataset using your eigenvectors. Reproject the dataset down to 2 dimensions.

In [29]:
eigenvectors_sorted[:2]


array([[-0.02848905, -0.16532108,  0.02135748, -0.18972574, -0.96716354],
       [-0.2001224 , -0.63218494,  0.25420475, -0.65862454,  0.24877074]])

## Summary

Well done! You've now coded PCA on your own using NumPy! With that, it's time to look at further application of PCA.