# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a Dot Product-type matrix multiplication. Understanding these properties will become useful as you move forward with machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication is distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [10]:
import numpy as np

A = np.array([[1, 1], [2, 2]])
B = np.array([[3], [4]])
C = np.array([[5], [6]])

A.dot(B+C) == (A.dot(B)+A.dot(C))


array([[ True],
       [ True]])

## Associative Property - matrix multiplication is associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [14]:
B = np.array([[1, 1], [2, 2]])

A.dot(B.dot(C)) == (A.dot(B)).dot(C)

array([[ True],
       [ True]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [17]:
B = np.array([[1, 1], [3, 3]])

A.dot(B) == B.dot(A)

array([[False, False],
       [False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [27]:
x = np.array([[2],[4],[6]])
y = np.array([[1],[3],[5]])

left = np.transpose(x).dot(y)
right = np.transpose(y).dot(x)

left==right

array([[ True]])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 